---
# tasks file for /usr/local/google/home/friasc/apigee-workspace/apigee-opdk-role-workspace/apigee-server-restart
- name: Restarting node now
  become: yes
  shell: sleep 2 && reboot now
  async: 1
  poll: 0

- name: Waiting for server to complete restarting
  become: no
  local_action: wait_for
  args:
    host: '{{ ansible_host }}'
    port: 22
    state: started
    delay: "{{ server_restart_delay | d(15) }}"
    timeout: '{{ server_restart_timeout | d(90) }}'

- name: Provide server processes with a few more seconds...
  become: no
  local_action: pause
  args:
    seconds: "{{ server_restart_extra_pause | d(5) }}"
    prompt: "Providing any remaining server startup processes with 5 more seconds..."

- name: Report server started
  debug:
    msg: "Server should now be running."
